import './twin-shell.css';
import type {DroneMissionStatus,MissionDestination,MissionRequest,PlannedRoute,RouteKind,WeatherSnapshot} from '../low-altitude-types.ts';
import type {FleetStation} from '../low-altitude-stations.ts';

export type TwinViewMode='home'|'rotate'|'pan'|'drone';
export type TwinTelemetry={fps:number;longitude:number;latitude:number;altitude:number;meshes:number;overview?:TwinFleetMapData};
type TwinFleetMapData={extent?:[number,number,number,number];land?:number[][][][];coast?:number[][][];weather?:{windDirection:number;windSpeed:number};orders?:{aircraftIndex:number;phase:string;progress:number;destinationName:string;orderId:string;batteryPercent:number}[];units:{x:number;z:number;active:boolean;charging?:boolean;id:string}[];routes:{id:string;points:{x:number;z:number}[]}[]};
export type TwinLayer='warehouse'|'drone'|'airspace'|'weather';

type TwinShellOptions={
 destinations:MissionDestination[];
 stations?:FleetStation[];
 onViewChange:(mode:TwinViewMode)=>void;
 onExpandChange?:(expanded:boolean)=>void;
 onLayerChange?:(layer:TwinLayer,enabled:boolean)=>void;
 onFocusDrone?:(index:number)=>void;
 onPlanRequest?:(request:MissionRequest)=>void;
 onRouteSelect?:(route:RouteKind)=>void;
 onRouteFocus?:(route:RouteKind)=>void;
 onMissionStart?:(route:RouteKind)=>void;
 onMissionCancel?:()=>void;
 onCancelOrder?:(orderId:string)=>void;
};

const FLEET=Array.from({length:5},(_,index)=>({id:'GR-'+String(index+1).padStart(2,'0'),pad:'P0'+(index+1)}));
const ICONS:Record<TwinViewMode,string>={
 home:'<path d="M4 11.2 12 4l8 7.2"/><path d="M6.5 10.4V20h11v-9.6M9.5 20v-5.5h5V20"/>',
 rotate:'<path d="M19.5 8.5A8 8 0 1 0 20 15"/><path d="m16 5 3.5 3.5L23 5"/>',
 pan:'<path d="M12 2v20M2 12h20"/><path d="m8 6 4-4 4 4M8 18l4 4 4-4M6 8l-4 4 4 4M18 8l4 4-4 4"/>',
 drone:'<path d="M5 8h14v8H5z"/><path d="M8 8V5h8v3M9 16v3M15 16v3M3 12h2M19 12h2"/>',
};
const WEATHER_DIRECTIONS=['北','东北','东','东南','南','西南','西','西北'];
const formatDistance=(meters:number)=>meters>=1000?(meters/1000).toFixed(meters>=10000?0:1)+' km':Math.round(meters)+' m';
const formatDirection=(degrees:number)=>WEATHER_DIRECTIONS[Math.round(((degrees%360)+360)%360/45)%8];
const sourceLabel=(source:WeatherSnapshot['source'])=>source==='live'?'实时天气':source==='cached'?'最近缓存':source==='offline'?'离线估算':'天气加载中';
const phaseLabel=(phase:DroneMissionStatus['phase'])=>({idle:'等待起飞',preflight:'起飞前检查',launching:'正在前往起点',loading:'已到起点 · 正在下降取货',enroute:'正在前往终点',rerouting:'正在重新规划',delivering:'已到终点 · 正在下降投递',returning:'正在返航并降落',completed:'任务已完成',cancelled:'任务已取消',aborted:'任务已中止',failed:'任务失败'}[phase]??'状态未知');

export function createTwinShell(host:HTMLElement,options:TwinShellOptions){
 const root=document.createElement('section');root.className='twin-shell';root.setAttribute('aria-label','深圳低空航路规划台');
 let destinations=[...options.destinations],selectedOriginId=destinations[0]?.id??'',selectedDestinationId=destinations[1]?.id??destinations[0]?.id??'',selectedRoute:RouteKind|null=null,currentRoutes:PlannedRoute[]=[];
 root.innerHTML=`
  <div class="twin-init-overlay" role="progressbar" aria-label="地图资源初始化进度" aria-valuemin="0" aria-valuemax="100" aria-valuenow="3"><div class="twin-init-card"><span class="twin-init-mark" aria-hidden="true"><i></i></span><small>SHENZHEN LOW-ALTITUDE ROUTING</small><h2>正在准备城市低空航路</h2><p id="twin-init-stage">正在创建三维场景</p><div class="twin-init-progress"><i id="twin-init-progress"></i></div><div class="twin-init-meta"><span>本地城市底座</span><b id="twin-init-percent">3%</b></div></div></div>
  <header class="twin-topbar">
   <div class="twin-brand"><div><small>LOW ALTITUDE ROUTING · SHENZHEN</small><h1>深圳低空航路中心</h1></div></div>
   <button class="twin-weather-pill" type="button" aria-label="查看深圳实时天气详情" aria-controls="twin-weather-card" data-weather-source="loading"><span class="twin-weather-icon" aria-hidden="true">◌</span><div><small id="twin-weather-source">天气加载中</small><b id="twin-weather-summary">正在获取深圳实况</b></div><strong id="twin-weather-temperature">--°</strong><span id="twin-weather-wind">-- m/s</span></button>
   <div class="twin-flight-index"><small>适飞指数</small><b id="twin-flight-index">--</b></div>
   <div class="twin-system-pill"><i></i><span id="twin-system-state" class="loading">初始化</span></div>
   <button class="twin-expand-button" type="button" aria-pressed="false" aria-label="进入沉浸地图"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 3H3v5M16 3h5v5M21 16v5h-5M3 16v5h5"/></svg><span>沉浸地图</span></button>
  </header>
  <aside class="twin-task-card" aria-label="配送任务设置">
   <div class="twin-card-title"><div><small>01 · ORDERS</small><h2>订单管理</h2></div><button id="twin-new-order" class="twin-new-order" type="button">新建订单</button></div><div id="twin-order-form-state" class="twin-order-form-state">新建订单后填写起点、终点和货物信息</div>
   <section id="twin-weather-card" class="twin-weather-card" data-weather-source="loading" aria-label="深圳实时天气"><div class="twin-weather-card-head"><div><small>LIVE WEATHER · SHENZHEN</small><b id="twin-weather-detail-source">天气加载中</b></div><span id="twin-weather-observed">同步中</span></div><strong id="twin-weather-card-summary">正在获取深圳实况</strong><div class="twin-weather-grid"><span><small>降水</small><b id="twin-weather-rain">-- mm</b></span><span><small>风向</small><b id="twin-weather-direction">--</b></span><span><small>风速</small><b id="twin-weather-speed">-- m/s</b></span><span><small>阵风</small><b id="twin-weather-gust">-- m/s</b></span></div><p id="twin-weather-impact">天气因素将计入航线评分。</p></section>
   <div id="twin-order-form" class="twin-order-form" hidden>
    <label class="twin-field twin-destination-field"><span>配送起点 · 输入地图地点</span><div class="twin-search-wrap"><i>A</i><input id="twin-origin-search" type="search" autocomplete="off" placeholder="搜索道路、地标、公园或社区" aria-label="搜索配送起点"/><button id="twin-clear-origin" type="button" aria-label="清除起点">×</button></div><div id="twin-origin-suggestions" class="twin-destination-suggestions" role="listbox"></div><small id="twin-origin-selected" class="twin-destination-selected">已选择</small></label>
    <div class="twin-field twin-destination-field"><span>配送终点 · 输入地图地点</span><div class="twin-search-wrap"><i>B</i><input id="twin-destination-search" type="search" autocomplete="off" placeholder="搜索道路、地标、公园或社区" aria-label="搜索配送终点"/><button id="twin-clear-destination" type="button" aria-label="清除终点">×</button></div><div id="twin-destination-suggestions" class="twin-destination-suggestions" role="listbox"></div><small id="twin-destination-selected" class="twin-destination-selected">已选择</small></div>
    <div class="twin-mission-row"><label class="twin-field"><span>货物名称</span><input id="twin-cargo-description" type="text" maxlength="80" placeholder="例如：餐饮配送箱" value="标准配送货物" aria-label="货物名称"></label><label class="twin-field"><span>重量 kg</span><input id="twin-cargo-weight" type="number" min="0.1" max="4.5" step="0.1" value="1.0" aria-label="货物重量"></label></div>
    <div class="twin-mission-row"><label class="twin-field"><span>体积 L</span><input id="twin-cargo-volume" type="number" min="0.1" max="40" step="0.1" value="8" aria-label="货物体积"></label><label class="twin-field"><span>时效</span><select id="twin-cargo-priority" aria-label="配送时效"><option value="standard">标准</option><option value="express">加急</option><option value="medical">医疗优先</option></select></label></div>
    <div class="twin-load twin-auto-dispatch"><span>调度策略</span><b>自动匹配无人机</b></div>
    <button id="twin-plan-route" class="twin-plan-button" type="button"><span>计算候选航线</span><small>建筑 · 地形 · 空域 · 实时天气</small></button>
   </div>
   <div class="twin-mission-orders"><div class="twin-orders-head"><b>执行中订单</b><span id="twin-active-order-count">0</span></div><div id="twin-active-orders" class="twin-active-orders"><small>暂无执行中的订单</small></div></div>
   <details class="twin-layer-drawer"><summary>地图图层与无人机</summary><div class="twin-layer-grid"><label><input type="checkbox" data-layer="warehouse" checked>仓库</label><label><input type="checkbox" data-layer="drone" checked>无人机</label><label><input type="checkbox" data-layer="airspace" checked>禁飞区/警戒区</label><label><input type="checkbox" data-layer="weather" checked>天气风险</label></div><div class="twin-airspace-legend" aria-label="空域图例"><span><i class="restricted"></i>禁飞区 <b>3</b></span><span><i class="caution"></i>警戒区 <b>1</b></span></div><div class="twin-drone-shortcuts">${FLEET.map((item,index)=>`<button type="button" data-focus-drone="${index}" aria-label="查看 ${item.id}">${index+1}</button>`).join('')}</div></details>
  </aside>
  <aside class="twin-route-panel" aria-label="候选航线">
   <div class="twin-card-title"><div><small>02 · ROUTES</small><h2>候选航线</h2></div><span id="twin-route-count">0 / 3</span></div>
   <div id="twin-route-state" class="twin-route-empty"><span aria-hidden="true">↗</span><b>等待任务</b><p>输入配送终点后，将同时计算最快、最低风险和综合方案。</p></div>
   <div id="twin-route-list" class="twin-route-list"></div><section id="twin-overview-map" class="twin-overview-map" aria-label="城市范围、航线与全部无人机俯瞰图"><div class="twin-overview-map-head"><small>LIVE OVERVIEW</small><b>全局运行态势</b></div><canvas id="twin-overview-canvas" width="320" height="180"></canvas><div class="twin-overview-legend"><span><i class="outline"></i>城市范围</span><span><i class="route"></i>进行中航线</span><span><i class="uav"></i>全部无人机</span></div></section>
   <div class="twin-route-actions"><button id="twin-focus-route" type="button" disabled>查看完整航线</button><button id="twin-dispatch-route" type="button" disabled>开始配送</button><button id="twin-cancel-mission" type="button" hidden>取消任务</button><p>禁飞区为教学仿真空域，非官方运行数据。</p></div>
   <section id="twin-mission-status" class="twin-mission-status" data-phase="idle"><div><small>MISSION STATUS</small><b id="twin-mission-phase">等待起飞</b></div><strong id="twin-mission-percent">0%</strong><div class="twin-mission-progress"><i id="twin-mission-progress"></i></div><p id="twin-mission-detail">选择路线后开始配送，系统将沿航线飞行并完成投递。</p></section>
  </aside>
  <nav class="twin-view-toolbar" aria-label="地图视角">${(['home','rotate','pan'] as ('home'|'rotate'|'pan')[]).map(mode=>`<button type="button" data-twin-view="${mode}" aria-pressed="${mode==='home'}"><svg viewBox="0 0 24 24" aria-hidden="true">${ICONS[mode]}</svg><span>${({home:'复位',rotate:'旋转',pan:'平移'} as Record<'home'|'rotate'|'pan',string>)[mode]}</span></button>`).join('')}<small id="twin-view-hint">左拖旋转 · 右拖平移 · 滚轮缩放</small></nav>
  <div class="twin-map-label-layer" aria-hidden="true"></div>
  <section id="twin-map-weather-hud" class="twin-map-weather-hud" data-weather-source="loading" aria-label="地图实时风场"><div class="twin-map-weather-icon" aria-hidden="true">↗</div><div><small>MAP WEATHER · LIVE</small><b id="twin-map-weather-summary">实时风场加载中</b><span id="twin-map-weather-metrics">风速 -- · 降水 --</span></div><strong id="twin-map-weather-index">--</strong></section>
  <section id="twin-drone-follow-badge" class="twin-drone-follow-badge" hidden aria-live="polite"><small>DRONE FOLLOW · LIVE</small><b id="twin-drone-follow-label">无人机跟随视角</b><span>沿航线观察 · 左拖环绕 · 右拖平移</span></section>
<footer class="twin-statusbar"><span><i class="online"></i><b id="twin-status-source">本地三维城市底座</b></span><span id="twin-coordinate">114.0250° E · 22.5360° N</span><span>相机 <b id="twin-altitude">-- m</b></span><span>场景 <b id="twin-meshes">--</b></span><span>帧率 <b id="twin-fps">-- FPS</b></span></footer>
  <div class="twin-notice" role="status" aria-live="polite"></div>`;
 host.replaceChildren(root);
 const query=<T extends HTMLElement>(selector:string)=>root.querySelector<T>(selector)!;
 const buttons=Array.from(root.querySelectorAll<HTMLButtonElement>('[data-twin-view]'));
 const planButton=query<HTMLButtonElement>('#twin-plan-route'),newOrderButton=query<HTMLButtonElement>('#twin-new-order'),orderForm=query<HTMLElement>('#twin-order-form'),focusRouteButton=query<HTMLButtonElement>('#twin-focus-route'),dispatchButton=query<HTMLButtonElement>('#twin-dispatch-route'),cancelMissionButton=query<HTMLButtonElement>('#twin-cancel-mission'),originSearchInput=query<HTMLInputElement>('#twin-origin-search'),originSuggestions=query<HTMLDivElement>('#twin-origin-suggestions'),selectedOrigin=query<HTMLElement>('#twin-origin-selected'),searchInput=query<HTMLInputElement>('#twin-destination-search'),suggestions=query<HTMLDivElement>('#twin-destination-suggestions'),selectedDestination=query<HTMLElement>('#twin-destination-selected'),cargoDescription=query<HTMLInputElement>('#twin-cargo-description'),cargoWeight=query<HTMLInputElement>('#twin-cargo-weight'),cargoVolume=query<HTMLInputElement>('#twin-cargo-volume'),cargoPriority=query<HTMLSelectElement>('#twin-cargo-priority');
 const orderFormState=query<HTMLElement>('#twin-order-form-state');newOrderButton.addEventListener('click',()=>{orderForm.hidden=false;newOrderButton.hidden=true;orderFormState.textContent='正在创建订单 · 填写起点、终点和货物信息';originSearchInput.focus();});
 const viewHint=query<HTMLElement>('#twin-view-hint'),droneFollowBadge=query<HTMLElement>('#twin-drone-follow-badge'),droneFollowLabel=query<HTMLElement>('#twin-drone-follow-label');
 let active:TwinViewMode='home',expanded=false,noticeTimer=0,initTimer=0,weatherAttentionTimer=0,missionActive=false;
 const overviewCanvas=query<HTMLCanvasElement>('#twin-overview-canvas'),overviewContext=overviewCanvas.getContext('2d');
  function drawPolygon(ctx:CanvasRenderingContext2D,rings:number[][][]|number[][],mapPoint:(x:number,z:number)=>{x:number;y:number}){
   const normalized=Array.isArray(rings[0]?.[0])?rings as number[][][]:[rings as number[][]];
   ctx.beginPath();
   for(const ring of normalized){ring.forEach((point,index)=>{const p=mapPoint(point[0],point[1]);index?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y);});ctx.closePath();}
  }
  function setFleetOverview(data:TwinFleetMapData){if(!overviewContext)return;const ctx=overviewContext,w=overviewCanvas.width,h=overviewCanvas.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#2b8fc4';ctx.fillRect(0,0,w,h);const extent=data.extent;const all=[...data.units.map(unit=>({x:unit.x,z:unit.z})),...data.routes.flatMap(route=>route.points)];if(extent){all.push({x:extent[0],z:extent[1]},{x:extent[2],z:extent[3]});}if(!all.length){ctx.fillStyle='#dcebe7';ctx.font='11px "Microsoft YaHei",sans-serif';ctx.textAlign='center';ctx.fillText('正在加载城市范围',w/2,h/2);return;}const xs=all.map(point=>point.x),zs=all.map(point=>point.z),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs),scale=Math.min((w-28)/Math.max(1,maxX-minX),(h-28)/Math.max(1,maxZ-minZ)),mapPoint=(x:number,z:number)=>({x:14+(x-minX)*scale,y:14+(z-minZ)*scale});
   if(data.land?.length){ctx.fillStyle='#fff';ctx.strokeStyle='#d5e3df';ctx.lineWidth=1;for(const polygon of data.land){drawPolygon(ctx,polygon,mapPoint);ctx.fill('evenodd');ctx.stroke();}}
   if(data.coast?.length){ctx.beginPath();for(const line of data.coast){line.forEach((point,index)=>{const p=mapPoint(point[0],point[1]);index?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y);});}ctx.strokeStyle='#e8f5f7';ctx.lineWidth=1.5;ctx.stroke();}
   if(data.weather){const center={x:w-32,y:28},radius=14,angle=(data.weather.windDirection-90)*Math.PI/180;ctx.beginPath();ctx.arc(center.x,center.y,radius,0,Math.PI*2);ctx.fillStyle='#ffffffbb';ctx.fill();ctx.strokeStyle='#ffffff';ctx.stroke();ctx.beginPath();ctx.moveTo(center.x-Math.cos(angle)*9,center.y-Math.sin(angle)*9);ctx.lineTo(center.x+Math.cos(angle)*9,center.y+Math.sin(angle)*9);ctx.strokeStyle='#176989';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#176989';ctx.font='8px Bahnschrift,sans-serif';ctx.textAlign='center';ctx.fillText(`${Math.round(data.weather.windSpeed)} m/s`,center.x,center.y+27);}   if(!data.land?.length&&extent){ctx.beginPath();ctx.rect(mapPoint(extent[0],extent[1]).x,mapPoint(extent[0],extent[1]).y,(extent[2]-extent[0])*scale,(extent[3]-extent[1])*scale);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle='#d5e3df';ctx.stroke();}
   if(data.weather){const center={x:w-32,y:28},radius=14,angle=(data.weather.windDirection-90)*Math.PI/180;ctx.beginPath();ctx.arc(center.x,center.y,radius,0,Math.PI*2);ctx.fillStyle='#ffffffbb';ctx.fill();ctx.strokeStyle='#ffffff';ctx.stroke();ctx.beginPath();ctx.moveTo(center.x-Math.cos(angle)*9,center.y-Math.sin(angle)*9);ctx.lineTo(center.x+Math.cos(angle)*9,center.y+Math.sin(angle)*9);ctx.strokeStyle='#176989';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#176989';ctx.font='8px Bahnschrift,sans-serif';ctx.textAlign='center';ctx.fillText(`${Math.round(data.weather.windSpeed)} m/s`,center.x,center.y+27);}   ctx.lineWidth=1.8;ctx.strokeStyle='#c87817';for(const route of data.routes){if(route.points.length<2)continue;ctx.beginPath();route.points.forEach((point,index)=>{const p=mapPoint(point.x,point.z);index?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y);});ctx.stroke();}for(const unit of data.units){const p=mapPoint(unit.x,unit.z);ctx.beginPath();ctx.fillStyle=unit.active?'#d08b28':unit.charging?'#278da1':'#627873';ctx.arc(p.x,p.y,unit.active?4:3.5,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=1;ctx.stroke();ctx.fillStyle='#365c58';ctx.font='8px Bahnschrift,sans-serif';ctx.textAlign='left';ctx.fillText(unit.id.replace('GR-',''),p.x+6,p.y+3);}}

 function setActiveOrders(items:{aircraftIndex:number;phase:string;progress:number;destinationName:string;orderId:string;batteryPercent:number}[]){const host=query<HTMLElement>('#twin-active-orders'),count=query<HTMLElement>('#twin-active-order-count');count.textContent=String(items.length);host.innerHTML=items.length?items.map(item=>`<div class="twin-active-order"><div><b>${item.orderId||'配送订单'}</b><small>GR-UAV-${String(item.aircraftIndex+1).padStart(2,'0')} · ${item.destinationName}</small></div><span>${Math.round(item.progress*100)}%</span><button type="button" data-follow-active="${item.aircraftIndex}">跟随</button><button type="button" data-cancel-active="${item.orderId}">取消订单</button></div>`).join(''):'<small>暂无执行中的订单</small>';host.querySelectorAll<HTMLButtonElement>('[data-follow-active]').forEach(button=>button.addEventListener('click',()=>options.onFocusDrone?.(Number(button.dataset.followActive))));host.querySelectorAll<HTMLButtonElement>('[data-cancel-active]').forEach(button=>button.addEventListener('click',()=>options.onCancelOrder?.(button.dataset.cancelActive!)));}
 function setMode(mode:TwinViewMode){active=mode;for(const button of buttons)button.setAttribute('aria-pressed',String(button.dataset.twinView===mode));viewHint.textContent=mode==='drone'?'无人机跟随 · 左拖环绕 · 右拖平移':'左拖旋转 · 右拖平移 · 滚轮缩放';}
 function setDroneFollow(index:number|null){droneFollowBadge.hidden=index===null;if(index!==null)droneFollowLabel.textContent=`GR-UAV-${String(index+1).padStart(2,'0')} · 跟随航线`;}
 for(const button of buttons)button.addEventListener('click',()=>{const mode=button.dataset.twinView as TwinViewMode;setMode(mode);options.onViewChange(mode);});
 function notify(message:string){const notice=query('.twin-notice');notice.textContent=message;notice.classList.add('visible');window.clearTimeout(noticeTimer);noticeTimer=window.setTimeout(()=>notice.classList.remove('visible'),3200);}
 function searchText(value:string){return value.normalize('NFKC').toLocaleLowerCase().replace(/[\s,，。.!！?？、/\\|·•:：;；()[\]{}<>《》“”‘’'"`~·_-]+/g,'');}
 function renderPlaceSuggestions(value:string,target:HTMLDivElement,kind:'origin'|'destination'){const normalized=searchText(value);const matches=destinations.filter(destination=>{if(!normalized)return true;const name=searchText(destination.name),detail=searchText(destination.detail),haystack=`${name}${detail}`;return haystack.includes(normalized)||normalized.includes(name)||normalized.split(/[市区县街道乡镇]+/).filter(Boolean).some(token=>token.length>1&&(name.includes(token)||detail.includes(token)));}).slice(0,8);target.innerHTML=matches.map(destination=>`<button type="button" role="option" data-${kind}-id="${destination.id}"><b>${destination.name}</b><small>${destination.detail}</small></button>`).join('');target.hidden=matches.length===0;for(const button of Array.from(target.querySelectorAll<HTMLButtonElement>(`[data-${kind}-id]`)))button.addEventListener('click',()=>kind==='origin'?selectOrigin(button.dataset.originId!):selectDestination(button.dataset.destinationId!));}
 function renderSuggestions(value=searchInput.value){renderPlaceSuggestions(value,suggestions,'destination');}
 function selectOrigin(id:string){const destination=destinations.find(item=>item.id===id);if(!destination)return;selectedOriginId=id;originSearchInput.value=destination.name;selectedOrigin.textContent=`已选择：${destination.name} · ${destination.detail}`;originSuggestions.hidden=true;}
 function selectDestination(id:string){const destination=destinations.find(item=>item.id===id);if(!destination)return;selectedDestinationId=id;searchInput.value=destination.name;selectedDestination.textContent=`已选择：${destination.name} · ${destination.detail}`;suggestions.hidden=true;}
 originSearchInput.addEventListener('input',()=>renderPlaceSuggestions(originSearchInput.value,originSuggestions,'origin'));originSearchInput.addEventListener('focus',()=>renderPlaceSuggestions(originSearchInput.value,originSuggestions,'origin'));originSearchInput.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();const first=originSuggestions.querySelector<HTMLButtonElement>('[data-origin-id]');if(first)selectOrigin(first.dataset.originId!);}});query<HTMLButtonElement>('#twin-clear-origin').addEventListener('click',()=>{originSearchInput.value='';selectedOriginId='';selectedOrigin.textContent='请输入起点地点';renderPlaceSuggestions('',originSuggestions,'origin');originSearchInput.focus();});
 searchInput.addEventListener('input',()=>renderSuggestions());searchInput.addEventListener('focus',()=>renderSuggestions());searchInput.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();const first=suggestions.querySelector<HTMLButtonElement>('[data-destination-id]');if(first)selectDestination(first.dataset.destinationId!);}});query<HTMLButtonElement>('#twin-clear-destination').addEventListener('click',()=>{searchInput.value='';selectedDestinationId='';selectedDestination.textContent='请输入终点地点';renderSuggestions('');searchInput.focus();});
 const expandButton=query<HTMLButtonElement>('.twin-expand-button');function setExpanded(next:boolean){expanded=next;root.classList.toggle('map-expanded',expanded);expandButton.setAttribute('aria-pressed',String(expanded));expandButton.setAttribute('aria-label',expanded?'恢复航路面板':'进入沉浸地图');expandButton.querySelector('span')!.textContent=expanded?'恢复面板':'沉浸地图';options.onExpandChange?.(expanded);notify(expanded?'沉浸地图已开启':'任务与航线面板已恢复');}expandButton.addEventListener('click',()=>setExpanded(!expanded));
 root.querySelectorAll<HTMLButtonElement>('[data-focus-drone]').forEach(button=>button.addEventListener('click',()=>options.onFocusDrone?.(Number(button.dataset.focusDrone))));root.querySelectorAll<HTMLInputElement>('[data-layer]').forEach(input=>input.addEventListener('change',()=>options.onLayerChange?.(input.dataset.layer as TwinLayer,input.checked)));
 planButton.addEventListener('click',()=>{if(!selectedOriginId){notify('请先选择配送起点');originSearchInput.focus();return;}if(!selectedDestinationId){notify('请先选择配送终点');searchInput.focus();return;}if(selectedOriginId===selectedDestinationId){notify('起点和终点不能相同');return;}const weightKg=Number(cargoWeight.value),volumeLiters=Number(cargoVolume.value);if(!Number.isFinite(weightKg)||weightKg<=0||weightKg>4.5){notify('货物重量必须在 0.1–4.5 kg 之间');cargoWeight.focus();return;}if(!Number.isFinite(volumeLiters)||volumeLiters<=0||volumeLiters>40){notify('货物体积必须在 0.1–40 L 之间');cargoVolume.focus();return;}options.onPlanRequest?.({originId:selectedOriginId,destinationId:selectedDestinationId,minimumBatteryPercent:25,cargo:{orderId:`SZ-${Date.now().toString(36).toUpperCase()}`,description:cargoDescription.value.trim()||'标准配送货物',weightKg,volumeLiters,priority:cargoPriority.value as 'standard'|'express'|'medical'}});newOrderButton.hidden=false;orderForm.hidden=true;orderFormState.textContent='订单已加入航线规划';});focusRouteButton.addEventListener('click',()=>{if(selectedRoute)options.onRouteFocus?.(selectedRoute);});dispatchButton.addEventListener('click',()=>{if(selectedRoute)options.onMissionStart?.(selectedRoute);});cancelMissionButton.addEventListener('click',()=>options.onMissionCancel?.());
 const weatherPill=query<HTMLButtonElement>('.twin-weather-pill'),weatherCard=query<HTMLElement>('#twin-weather-card');weatherPill.addEventListener('click',()=>{weatherCard.scrollIntoView({block:'nearest',behavior:'smooth'});weatherCard.classList.add('attention');window.clearTimeout(weatherAttentionTimer);weatherAttentionTimer=window.setTimeout(()=>weatherCard.classList.remove('attention'),1200);});
 function setLoadingProgress(stage:string,percent:number){const overlay=root.querySelector<HTMLElement>('.twin-init-overlay');if(!overlay)return;const value=Math.max(0,Math.min(100,Math.round(percent)));query('#twin-init-stage').textContent=stage;query('#twin-init-percent').textContent=value+'%';query<HTMLElement>('#twin-init-progress').style.width=value+'%';overlay.setAttribute('aria-valuenow',String(value));if(value>=100){overlay.classList.add('complete');window.clearTimeout(initTimer);initTimer=window.setTimeout(()=>overlay.remove(),650);}}
 function setLoadingError(message:string){const overlay=query('.twin-init-overlay');overlay.classList.add('error');query('#twin-init-stage').textContent=message;query('#twin-init-percent').textContent='ERROR';}
 function setSystemState(label:string,online:boolean,detail=label){const state=query('#twin-system-state');state.textContent=label;state.classList.toggle('loading',!online);state.title=detail;root.querySelector('.twin-system-pill')?.classList.toggle('online',online);root.classList.toggle('is-initializing',!online);}
 function setWeather(weather:WeatherSnapshot){const pill=query('.twin-weather-pill'),mapHud=query<HTMLElement>('#twin-map-weather-hud');pill.dataset.weatherSource=weather.source;weatherCard.dataset.weatherSource=weather.source;mapHud.dataset.weatherSource=weather.source;const label=sourceLabel(weather.source),direction=Number.isFinite(weather.windDirection)?formatDirection(weather.windDirection)+'风':'--',speed=Number.isFinite(weather.windSpeed)?`${weather.windSpeed.toFixed(1)} m/s`:'--';query('#twin-weather-source').textContent=label;query('#twin-weather-detail-source').textContent=label;query('#twin-weather-summary').textContent=weather.summary;query('#twin-weather-card-summary').textContent=weather.summary;query('#twin-weather-temperature').textContent=Number.isFinite(weather.temperature)?Math.round(weather.temperature)+'°':'--°';query('#twin-weather-wind').textContent=Number.isFinite(weather.windSpeed)?`${direction} ${speed}`:'-- m/s';query('#twin-flight-index').textContent=Number.isFinite(weather.flightIndex)?String(Math.round(weather.flightIndex)):'--';query('#twin-flight-index').className=weather.flightIndex>=75?'safe':weather.flightIndex>=55?'warn':'danger';query('.twin-weather-icon').textContent=weather.precipitation>.1?'雨':weather.windSpeed>8?'风':'晴';query('#twin-weather-rain').textContent=Number.isFinite(weather.precipitation)?`${weather.precipitation.toFixed(1)} mm`:'--';query('#twin-weather-direction').textContent=direction;query('#twin-weather-speed').textContent=speed;query('#twin-weather-gust').textContent=Number.isFinite(weather.windGust)?`${weather.windGust.toFixed(1)} m/s`:'--';query('#twin-weather-observed').textContent=weather.observedAt?new Date(weather.observedAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}):'--';query('#twin-weather-impact').textContent=weather.precipitation>.1?`已计入降水 ${weather.precipitation.toFixed(1)} mm；${weather.windSpeed>=8?'风速偏高，路线会提高安全权重。':'路线会按风向修正。'}`:`降水较低；路线会按${direction} ${speed} 修正耗时。`;query('#twin-map-weather-summary').textContent=weather.summary;query('#twin-map-weather-metrics').textContent=`${direction} · 风速 ${speed} · 降水 ${Number.isFinite(weather.precipitation)?weather.precipitation.toFixed(1):'--'} mm`;query('#twin-map-weather-index').textContent=Number.isFinite(weather.flightIndex)?`${Math.round(weather.flightIndex)} /100`:'--';query('.twin-map-weather-icon').textContent=weather.precipitation>.1?'☂':weather.windSpeed>8?'⚠':'↗';}
 function setPlanning(planning:boolean,message='正在分析城市低空环境'){planButton.disabled=planning;planButton.querySelector('span')!.textContent=planning?'正在计算三条航线…':'计算候选航线';const state=query('#twin-route-state');state.hidden=false;state.className=planning?'twin-route-empty planning':'twin-route-empty';state.innerHTML=planning?`<span aria-hidden="true">···</span><b>${message}</b><p>正在综合建筑净空、地形、仿真空域和天气。</p>`:'<span aria-hidden="true">↗</span><b>等待任务</b><p>输入配送终点后，将同时计算最快、最低风险和综合方案。</p>';}
 function selectRoute(routeId:RouteKind,emit=true){selectedRoute=routeId;root.querySelectorAll<HTMLButtonElement>('[data-route-id]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.routeId===routeId)));focusRouteButton.disabled=false;dispatchButton.disabled=false;if(emit)options.onRouteSelect?.(routeId);}
 function setRoutes(routes:PlannedRoute[],preferred:RouteKind='balanced'){currentRoutes=routes;const list=query('#twin-route-list'),state=query('#twin-route-state');query('#twin-route-count').textContent=`${routes.length} / 3`;state.hidden=routes.length>0;list.innerHTML=routes.map(route=>`<button class="twin-route-card ${route.id}" type="button" data-route-id="${route.id}" aria-pressed="${route.id===preferred}"><span class="twin-route-line" aria-hidden="true"></span><div class="twin-route-head"><span>${route.badge}</span><b>${route.name}</b><strong>${Math.round(route.riskScore)}</strong></div><div class="twin-route-metrics"><b>${formatDistance(route.distanceMeters)}</b><span>${Math.max(1,Math.round(route.durationMinutes))} 分钟</span><span>${Math.round(route.cruiseAltitude)} m · ${route.cruiseSpeed.toFixed(1)} m/s</span></div><div class="twin-route-tags"><em>${route.weatherImpact>4?'天气已计入':'天气良好'}</em><em>${route.headwind>2?'逆风修正':'风向友好'}</em></div><p>${route.reasons.slice(0,2).join(' · ')}</p></button>`).join('');list.querySelectorAll<HTMLButtonElement>('[data-route-id]').forEach(button=>button.addEventListener('click',()=>selectRoute(button.dataset.routeId as RouteKind)));selectedRoute=routes.some(route=>route.id===preferred)?preferred:routes[0]?.id??null;if(selectedRoute)selectRoute(selectedRoute,false);else{focusRouteButton.disabled=true;dispatchButton.disabled=true;}planButton.disabled=false;planButton.querySelector('span')!.textContent='重新计算候选航线';}
 function setMissionStatus(status:DroneMissionStatus){missionActive=!['idle','completed','cancelled'].includes(status.phase);query<HTMLElement>('.twin-route-panel').dataset.missionActive=String(missionActive);const panel=query<HTMLElement>('#twin-mission-status');panel.dataset.phase=status.phase;query('#twin-mission-phase').textContent=phaseLabel(status.phase);query('#twin-mission-percent').textContent=Math.round(status.progress*100)+'%';query<HTMLElement>('#twin-mission-progress').style.width=Math.round(status.progress*100)+'%';query('#twin-mission-detail').textContent=status.phase==='idle'?'填写货物信息并选择航线后开始配送。':status.phase==='completed'||status.phase==='cancelled'?`订单 ${status.orderId||'未编号'} · ${status.safetyMessage} · 剩余电量 ${Math.round(status.batteryPercent)}%`:`${status.destinationName||'配送任务'} · ${status.safetyMessage} · 剩余 ${formatDistance(status.distanceRemaining)} · 电量 ${Math.round(status.batteryPercent)}% · 返航预计 ${Math.round(status.estimatedReturnBattery)}%`;root.querySelectorAll<HTMLButtonElement>('[data-route-id]').forEach(button=>button.disabled=missionActive);cancelMissionButton.hidden=!missionActive;dispatchButton.hidden=false;dispatchButton.disabled=!selectedRoute;focusRouteButton.disabled=!selectedRoute;planButton.disabled=false;}
 function setDestinations(next:MissionDestination[]){destinations=[...next];if(!destinations.some(item=>item.id===selectedOriginId))selectOrigin(destinations[0]?.id??'');if(!destinations.some(item=>item.id===selectedDestinationId))selectDestination(destinations[1]?.id??destinations[0]?.id??'');renderSuggestions();renderPlaceSuggestions(originSearchInput.value,originSuggestions,'origin');}
 function update(telemetry:TwinTelemetry){setActiveOrders(telemetry.overview?.orders??[]);query('#twin-coordinate').textContent=`${telemetry.longitude.toFixed(4)}° E · ${telemetry.latitude.toFixed(4)}° N`;query('#twin-altitude').textContent=Math.max(0,telemetry.altitude).toFixed(0)+' m';query('#twin-meshes').textContent=telemetry.meshes.toLocaleString('zh-CN');setFleetOverview(telemetry.overview??{units:[],routes:[]});}
 return {root,setMode,setDroneFollow,setExpanded,setLoadingProgress,setLoadingError,setSystemState,setWeather,setPlanning,setRoutes,setMissionStatus,setDestinations,selectRoute,notify,update,get mode(){return active;},get expanded(){return expanded;},get selectedRoute(){return currentRoutes.find(route=>route.id===selectedRoute)??null;},get selectedDestinationId(){return selectedDestinationId;},dispose(){window.clearTimeout(noticeTimer);window.clearTimeout(initTimer);root.remove();}};
}
